# Generated by Django 3.2.8 on 2022-12-27 10:00

import catalog_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SlugField(max_length=36, unique=True, verbose_name='Идентификатор')),
                ('code', models.CharField(max_length=150, verbose_name='Наименование')),
                ('name', models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='Наименование')),
                ('cpu_slug', models.SlugField(blank=True, default='', max_length=70, null=True, verbose_name='ЧПУ_Url')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SlugField(max_length=36, unique=True, verbose_name='Идентификатор')),
                ('code', models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='Код')),
                ('art', models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='Артикул')),
                ('name', models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='Наименование')),
                ('okei', models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='Единица измерения')),
                ('cpu_slug', models.SlugField(blank=True, default='', max_length=70, null=True, verbose_name='ЧПУ_Url')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SlugField(max_length=36, unique=True, verbose_name='Идентификатор')),
                ('title', models.CharField(blank=True, default=None, max_length=36, null=True, verbose_name='Наименование')),
                ('image', models.ImageField(default=None, upload_to=catalog_app.models.get_image_name, verbose_name='Изображение')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.good', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
