# Generated by Django 3.2.8 on 2022-12-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0002_alter_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Наименование'),
        ),
    ]
