# Generated by Django 3.2.8 on 2022-12-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0003_alter_good_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='cpu_slug',
            field=models.SlugField(blank=True, default='', max_length=256, null=True, verbose_name='ЧПУ_Url'),
        ),
    ]
