# Generated by Django 3.2.8 on 2022-12-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0004_alter_good_cpu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cpu_slug',
            field=models.SlugField(blank=True, default='', max_length=256, null=True, verbose_name='ЧПУ_Url'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Наименование'),
        ),
    ]
