# Generated by Django 3.2.8 on 2022-12-27 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0006_auto_20221227_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SlugField(max_length=36, unique=True, verbose_name='Идентификатор')),
                ('code', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Код')),
                ('name', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип цен',
                'verbose_name_plural': 'Типы цен',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.good', verbose_name='Товар')),
                ('price_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.pricetype', verbose_name='Тип цены')),
            ],
            options={
                'verbose_name': 'Цена товара',
                'verbose_name_plural': 'Цены товаров',
                'unique_together': {('good', 'price_type')},
            },
        ),
    ]
