# Generated by Django 3.2.8 on 2022-12-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0008_division_stockbalance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockbalance',
            options={'verbose_name': 'Остаток товара', 'verbose_name_plural': 'Остатки товаров'},
        ),
    ]
