# Generated by Django 3.2.8 on 2023-01-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0009_alter_stockbalance_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='image',
        ),
        migrations.AddField(
            model_name='picture',
            name='src',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Изображение'),
        ),
    ]
