# Generated by Django 3.2.8 on 2023-02-01 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0010_auto_20230118_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SlugField(max_length=36, unique=True, verbose_name='Идентификатор')),
                ('name', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Наименование')),
                ('cpu_slug', models.SlugField(blank=True, default='', max_length=256, null=True, verbose_name='ЧПУ_Url')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='manufacturer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog_app.manufacturer', verbose_name='Производитель'),
        ),
    ]
