# Generated by Django 3.2.8 on 2023-02-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0011_auto_20230201_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Сокращенное наименование'),
        ),
    ]
